version: '3.8'

services:
  api-predict:
    build: api/
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    networks:
      - app_network
    container_name: api-service

  webapp:
    build: webapp/
    environment:
      - API_URL=http://api-predict:8000
    depends_on:
      - api-predict
    ports:
        - 8501:8501
    networks:
      - app_network
    container_name: web-service

networks:
  app_network:
    driver: bridge